spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/employee_Management
    username: root
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: ALWAYS
